server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: leaveflow-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:leave_management}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:ROOT}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  jwt:
    secret: ${JWT_SECRET:c2VjdXJlLWxlYXZlZmxvdy1kZW1vLXNlY3JldC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24tMjU2Yml0}
    access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION:3600000}
    refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION:604800000}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.leaveflow.backend: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

debug: true